#!/usr/bin/env bash

dir=$1
if [[ -z "$1" ]]; then
    dir=$(zoxide query -l)
fi

#selected=$(find $dir -mindepth 1 -maxdepth 4 -type d | fzf)
#selected=$(fd . $dir -d 1 -t d | fzf | sed "s:/$::")
selected=$(fd . $dir -d 1 -t d | gum filter --limit 1 --no-sort --fuzzy --height 50 --prompt='⚡' | sed "s:/$::")
if [[ -z "$selected" ]]; then
	exit 0
fi

selected_name=$(basename $selected | tr ":,. " "____")

switch_to() {
	if [[ -z "$TMUX" ]]; then
		tmux attach-session -t $selected_name
	else
		tmux switch-client -t $selected_name
	fi

}

if tmux has-session -t=$selected_name 2> /dev/null; then
	switch_to
	exit 0
fi

tmux new-session -ds $selected_name -c $selected
switch_to
tmux send-keys -t $selected_name "ready-tmux" ^M
